---

networks:
- name: default
  type: manual
  subnets:
  - range: ((network_range))
    gateway: ((network_gateway))
    reserved: [((reserverd_ranges))]
    dns: [((dns))]
    cloud_properties:
      net_id: ((network_id)

vm_types:
- name: large
  cloud_properties:
    instance_type: m1.large
- name: throuputramp_vm
  cloud_properties:
    instance_type: m1.medium
    ephemeral_disk:
      size: 10240


compilation:
  workers: 1
  reuse_compilation_vms: true
  vm_type: large
  network: throuputramp_network